eShop/eShop/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from eShopApp import views
from eShopApp.views import CustomLoginView
from eShopApp.views import register

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('register/', register, name='register'),
    path('admin/', admin.site.urls),
    path('products/', views.products, name="products"),
    path('products/delete/<int:product_id>', views.delete_product, name='delete_product'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<int:product_id>', views.edit_product, name='edit_product'),
    path('products/add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('shoppingCart/', views.shopping_cart, name="shopping_cart"),
    path('checkout/', views.checkout, name='checkout'),
    path('order_history/', views.order_history, name='order_history'),
    path('logout/', views.custom_logout, name='logout'),
]

eShop/eShopApp/models.py
from django.db import models
from django.contrib.auth.models import User
import random
import string


# PRODUCT
# CATEGORY
# SHOPPING CART
# ORDER
# Create your models here.

class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('customer', 'Buyer'),
        ('seller', 'Seller'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='regular')


class Category(models.Model):
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    SEX = [("M", "Male"),
            ("F", "Female"),
            ("U", "Unisex"),
            ]
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    price = models.IntegerField()
    img = models.URLField(max_length=255)
    stock = models.IntegerField()
    color = models.CharField(max_length=255)
    sex = models.CharField(max_length=1, choices=SEX)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        permissions = [
            ("custom_add_product", "Can add product"),
            ("custom_edit_product", "Can edit product"),
            ("custom_delete_product", "Can delete product")
            
        ]

    def __str__(self):
        return self.name + " " + self.desc + " " + str(self.price)


class ShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class ShoppingCartProduct(models.Model):
    shopping_cart = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.IntegerField()

    def __str__(self):
        return str(self.shopping_cart) + " " + str(self.product)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_number = models.CharField(max_length=255, unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.IntegerField()
    address = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self.generate_random_order_number()

        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.user) + " " + self.order_number


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.IntegerField()

    def __str__(self):
        return str(self.order) + " " + str(self.price)

eShop/eShopApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import UserProfile, Product
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    user_type = forms.ChoiceField(choices=UserProfile.USER_TYPE_CHOICES)

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('user_type',)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

eShop/eShopApp/views.py
from django.contrib.auth import login

from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import Group, Permission
import random, string
from datetime import datetime
from .forms import CustomUserCreationForm, ProductForm
from .models import UserProfile, Product, ShoppingCart, ShoppingCartProduct, Order, OrderProduct


# Create your views here.


# LOGIN, REGISTER AND LOG OUT
class CustomLoginView(LoginView):
    template_name = 'registration/login.html'
    success_url = reverse_lazy('products')


def custom_logout(request):
    logout(request)
    return redirect('login')


def register(request):
    if request.method == 'POST':
        print("DADA")
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user, user_type=form.cleaned_data['user_type'])
            if user_profile.user_type == 'customer':
                user.groups.add(Group.objects.get(name='Buyer'))
            elif user_profile.user_type == 'seller':
                user.groups.add(Group.objects.get(name='Seller'))
                user.user_permissions.add(Permission.objects.get(codename='custom_add_product'))
            login(request, user)
            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


# SELLER OPTIONS
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)


    if request.user.userprofile.user_type == 'seller':
        product.delete()

    return redirect('products')


def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products')
    else:
        form = ProductForm()

    return render(request, 'add_product.html', {'form': form})


def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products')
    else:
        form = ProductForm(instance=product)

    return render(request, 'edit_product.html', {'form': form})


# BUYER OPTIONS
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    shopping_cart, created = ShoppingCart.objects.get_or_create(user=request.user)
    shopping_cart_product = None
    error_message = None

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        if quantity < 1:
            error_message = "Invalid quantity"
        elif quantity > product.stock:
            error_message = "Quantity exceeds available stock"
        else:
            shopping_cart_product, created = ShoppingCartProduct.objects.get_or_create(
                shopping_cart=shopping_cart,
                product=product,
                defaults={'quantity': quantity, 'price': product.price},
            )
            error_message = "Successfully added to cart"
            if not created:
                shopping_cart_product.quantity += quantity
                if shopping_cart_product.quantity <= product.stock:
                    shopping_cart_product.save()
                    error_message = "Successfully added to cart"
                else:
                    error_message = "Quantity exceeds available stock"

    context = {
        'products': Product.objects.all(),
        'user': request.user,
        'error_message': error_message,  
    }
    return render(request, "products.html", context)


def shopping_cart(request):
    user = request.user
    shopping_cart_products = ShoppingCartProduct.objects.filter(shopping_cart__user=user)
    total_price = sum(item.quantity * item.product.price for item in shopping_cart_products)

    context = {'shopping_cart_products': shopping_cart_products,
               'total_price': total_price, }

    if request.method == 'POST':
        current_page_url = reverse('shopping_cart')
        item_id_to_delete = request.POST.get('item_id_to_delete')
        if item_id_to_delete:
            item_to_delete = ShoppingCartProduct.objects.filter(id=item_id_to_delete, shopping_cart__user=user).first()
            if item_to_delete:
                item_to_delete.delete()
                return redirect(current_page_url)

    return render(request, 'shopping_cart.html', context)


def checkout(request):
    user = request.user
    shopping_cart_products = ShoppingCartProduct.objects.filter(shopping_cart__user=user)
    total_price = sum(item.quantity * item.product.price for item in shopping_cart_products)

    if request.method == 'POST':
        user_input = request.POST.get('user')
        address = request.POST.get('address')

       
        order_number = "#" + ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(10))

        
        order = Order.objects.create(
            user=user,
            order_number=order_number,
            created_at=datetime.now(),
            total_price=total_price,
            address=address
        )

        
        for cart_product in shopping_cart_products:
            OrderProduct.objects.create(
                order=order,
                product=cart_product.product,
                quantity=cart_product.quantity,
                price=cart_product.product.price * cart_product.quantity
            )

    
        shopping_cart_products.delete()

  
        return redirect('products')

    context = {'shopping_cart_products': shopping_cart_products, 'total_price': total_price}
    return render(request, 'checkout.html', context)


def order_history(request):
    user = request.user
    orders = Order.objects.filter(user=user)

    context = {
        'orders': orders,
    }
    return render(request, 'order_history.html', context)


def products(request):
    categories = Product.objects.values_list('category__name', flat=True).distinct()
    selected_category = request.GET.get('category')
    filtered_products = Product.objects.all()

    if selected_category:
        if selected_category == '':
            selected_category = None
        else:
            filtered_products = Product.objects.filter(category__name=selected_category)

    return render(request, "products.html",
                  {'products': filtered_products, 'categories': categories, 'user': request.user,
                   'selected_category': selected_category})

eShop/eShopApp/templates/add_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Product</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #B5FFFF;
        }

        input {
            background-color: #B5FFFF;
            float: right;
        }

        select {
            background-color: #B5FFFF;
        }
    </style>

</head>
<body>
{% if user.is_authenticated %}
<div style="margin-top: 0px;margin-left: 0; margin-bottom: 20px; background-color: #FFF3F3; width: 100%; padding-top: 11px;
    justify-items: center;
    padding-left: 66px; height: 70px;">
    <h1 class="mb-4 font-italic font-weight-700"
        style="margin-left: 20px; font-family: 'Inter', sans-serif; display: inline">Blossom
        Beauty</h1>

    <form method="post" action="{% url 'logout' %}"
          style="display: inline; float: right; margin-right: 150px; margin-top: -5px;">
        {% csrf_token %}
        <button type="button" class="btn btn-primary mt-2 ml-auto shadow"
                style="background-color: #008787; margin-right: 20px; margin-bottom:8px"><a href="/products/"
                                                                                            class="text-white"
                                                                                            style="text-decoration: none;"><strong>Go
            Back</strong></a></button>
        <button type="submit" style="background-color: #008787" class="btn btn-primary ml-auto shadow">
            <strong>Logout</strong>
        </button>
    </form>
</div>
{% endif %}

<div class="container mt-4">

    <h1 class="font-italic font-weight-700" style="font-family: 'Inter', sans-serif;">Add Product</h1>
    <form method="post"
          style="width: 300px;text-align: left; border: 2px solid; padding: 10px; background-color: #00BFBF"
          class="rounded">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success shadow" style="background-color: #008787"><strong>Add new
            product</strong></button>
    </form>
</div>
</body>
</html>

eShop/eShopApp/templates/checkout.html
<!DOCTYPE html>
<html>
<head>
    <title>Checkout</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
    <style>
        .card-thick-border {
            border-width: 2px;
            border-color: black;

        }

        body {
            background-color: #B5FFFF;
        }

    </style>
</head>
<body>

{% if user.is_authenticated %}
<div style="margin-top: 0px;margin-left: 0; margin-bottom: 20px; background-color: #FFF3F3; width: 100%; padding-top: 11px;
    justify-items: center;
    padding-left: 66px; height: 70px;">
    <h1 class="mb-4 font-italic font-weight-700"
        style="margin-left: 20px; font-family: 'Inter', sans-serif; display: inline">Blossom
        Beauty</h1>

    <form method="post" action="{% url 'logout' %}"
          style="display: inline; float: right; margin-right: 133px; margin-top: -5px;">
        {% csrf_token %}
        <button type="button" class="btn btn-primary mt-2 ml-auto shadow-lg"
                style="background-color: #008787; margin-right: 20px; margin-bottom:8px"><a href="/products/"
                                                                                            class="text-white"
                                                                                            style="text-decoration: none;"><strong>Go
            Back</strong></a></button>
        <button type="submit" style="background-color: #008787" class="btn btn-primary ml-auto shadow-lg">
            <strong>Logout</strong>
        </button>
    </form>
</div>
{% endif %}
<div class="container mt-4">


    <h1>Checkout</h1>
    <form method="post" action="{% url 'checkout' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="user" class="form-label fw-bold">Username:</label>
            <input style="width: 400px" disabled type="text" id="user" name="user" value="{{ request.user.username }}"
                   class="form-control"
                   required>
        </div>
        <div class="mb-3">
            <label for="address" class="form-label fw-bold">Address:</label>
            <input style="width: 400px" type="text" id="address" name="address" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="card_number" class="form-label fw-bold">Card Number:</label>
            <input style="width: 400px" type="text" id="card_number" name="card_number" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="expiration_date" class="form-label fw-bold">Expiration Date:</label>
            <input style="width: 400px" type="text" id="expiration_date" name="expiration_date" placeholder="MM/YYYY"
                   class="form-control"
                   required>
        </div>
        <div class="mb-3">
            <label for="csv" class="form-label fw-bold">CVV:</label>
            <input style="width: 400px" type="text" id="csv" name="csv" class="form-control" required>
        </div>

        <h2 class="mt-4">Shopping Cart:</h2>
        <div class="d-flex flex-wrap">
            {% for cart_product in shopping_cart_products %}
            <div class="col-md-3">
                <ul class="list-group">
                    <li class="list-group-item card-thick-border"
                        style="margin-right: 5px; margin-bottom: 5px; background-color: #00BFBF">
                        <img src="{{ cart_product.product.img }}" alt="{{ cart_product.product.name }}"
                             class="mr-3 rounded"
                             width="100%" height="200px" style="margin-left: 0">
                        <div>
                            <h5 class="mb-1">{{ cart_product.product.name }}</h5>
                            <p class="mb-1"><strong>Quantity:</strong> {{ cart_product.quantity }}</p>
                            <p class="mb-0"><strong>Price:</strong> ${{ cart_product.price }}</p>
                        </div>
                    </li>
                </ul>
            </div>
            {% endfor %}
        </div>

        <h3 class="mt-2"><strong>Total Price: ${{ total_price }}</strong></h3>

        <button type="submit" class="btn btn-success mt-3"
                style="width: 100%; margin-bottom: 50px; background-color: #008787"><strong>Confirm</strong>
        </button>
    </form>


</div>
</body>
</html>

eShop/eShopApp/templates/edit_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Product</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #B5FFFF;
        }

        input {
            background-color: #B5FFFF;
            float: right;
        }

        select {
            background-color: #B5FFFF;
        }
    </style>
</head>
<body>

{% if user.is_authenticated %}
<div style="margin-top: 0px;margin-left: 0; margin-bottom: 20px; background-color: #FFF3F3; width: 100%; padding-top: 11px;
    justify-items: center;
    padding-left: 66px; height: 70px;">
    <h1 class="mb-4 font-italic font-weight-700"
        style="margin-left: 20px; font-family: 'Inter', sans-serif; display: inline">Blossom
        Beauty</h1>

    <form method="post" action="{% url 'logout' %}"
          style="display: inline; float: right; margin-right: 150px; margin-top: -5px;">
        {% csrf_token %}
        <button type="button" class="btn btn-primary mt-2 ml-auto shadow"
                style="background-color: #008787; margin-right: 20px; margin-bottom:8px"><a href="/products/"
                                                                                            class="text-white"
                                                                                            style="text-decoration: none;"><strong>Go
            Back</strong></a></button>
        <button type="submit" style="background-color: #008787" class="btn btn-primary ml-auto shadow">
            <strong>Logout</strong>
        </button>
    </form>
</div>
{% endif %}

<div class="container">

    <h1>Edit Product</h1>
    <form method="post"
          style="width: 300px;text-align: left; border: 2px solid; padding: 10px; background-color: #00BFBF"
          class="rounded">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success" style="background-color: #008787"><strong>Save Changes</strong>
        </button>
    </form>
</div>

</body>
</html>

eShop/eShopApp/templates/order_history.html
<!DOCTYPE html>
<html>
<head>
    <title>Order History</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
    <style>
        .card-thick-border {
            border-width: 3px;
            border-color: black;
        }

        body {
            background-color: #B5FFFF;
        }

    </style>
</head>
<body>

{% if user.is_authenticated %}
<div style="margin-top: 0px;margin-left: 0; margin-bottom: 20px; background-color: #FFF3F3; width: 100%; padding-top: 11px;
    justify-items: center;
    padding-left: 66px; height: 70px;">
    <h1 class="mb-4 font-italic font-weight-700"
        style="margin-left: 20px; font-family: 'Inter', sans-serif; display: inline">Blossom
        Beauty</h1>

    <form method="post" action="{% url 'logout' %}"
          style="display: inline; float: right; margin-right: 133px; margin-top: -5px;">
        {% csrf_token %}
        <button type="button" class="btn btn-primary mt-2 ml-auto shadow"
                style="background-color: #008787; margin-right: 20px; margin-bottom:8px"><a href="/products/"
                                                                                            class="text-white"
                                                                                            style="text-decoration: none;"><strong>Go
            Back</strong></a></button>
        <button type="submit" style="background-color: #008787" class="btn btn-primary ml-auto shadow">
            <strong>Logout</strong>
        </button>
    </form>
</div>
{% endif %}

<div class="container mt-4">

    <h1 class="mb-4 font-italic font-weight-700"
        style="font-family: 'Inter', sans-serif; display: inline">Order History</h1>
    {% if orders %}
    <div class="row row-cols-1 row-cols-md-3 g-3">
        {% for order in orders %}
        <div class="col">
            <div class="card card-thick-border">
                <div class="card-body" style="background-color: #00BFBF">
                    <h5 class="card-title"><strong>Order Number:</strong> {{ order.order_number }}</h5>
                    <p class="card-text"><strong>Created At:</strong> {{ order.created_at }}</p>
                    <p class="card-text"><strong>Address:</strong> {{ order.address }}</p>
                    <ul class="list-group">
                        {% for order_product in order.orderproduct_set.all %}
                        <li class="list-group-item rounded" style="background-color: #008787; margin-bottom: 5px">
                            <strong>{{ order_product.product.name }}</strong><br>
                            <strong>Quantity:</strong> {{ order_product.quantity }}<br>
                            <strong>Price:</strong> {{ order_product.price }}$<br>
                        </li>
                        {% endfor %}
                    </ul>
                    <p class="card-text"><strong>Total Price: {{ order.total_price }}$</strong></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h5 style="margin-left: 5px">You don't have any orders</h5>
    {% endif %}


</div>
</body>
</html>

eShop/eShopApp/templates/products.html
<!DOCTYPE html>
<html>
<head>
    <title>Product List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        body {
            background-color: #B5FFFF; 
        }

        .product-card {
            max-width: 300px; 
            margin: auto;

        }

    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
    <script>
        
        document.addEventListener("DOMContentLoaded", function () {
            
            var errorMessage = document.getElementById("error-message");

            if (errorMessage) {
                setTimeout(function () {
                    errorMessage.style.display = "none";
                }, 3000);
            }
        });
    </script>

</head>
<body>
{% if user.is_authenticated %}
<div style="margin-top: 0px;margin-left: 0; margin-bottom: 20px; background-color: #FFF3F3; width: 100%; padding-top: 11px;
    justify-items: center;
    padding-left: 66px; height: 70px;">
    <h1 class="mb-4 font-italic font-weight-700"
        style="margin-left: 20px; font-family: 'Inter', sans-serif; display: inline">Blossom
        Beauty</h1>

    <form method="post" action="{% url 'logout' %}" style="display: inline; float: right; margin-right: 150px;">
        {% csrf_token %}
        <button style="margin-left: 60px; margin-bottom: 20px; background-color: #008787; margin-top: 3px; "
                type="submit"
                class="btn btn-primary ml-auto shadow"><strong>Logout</strong>
        </button>
    </form>
</div>
{% endif %}

{% if user.userprofile.user_type == 'seller' %}
<a style="margin-bottom: 20px; margin-left: 90px; background-color: #008787" href="{% url 'add_product' %}"
   class="btn btn-primary ml-auto shadow"><strong>Add
    New Product</strong></a>
{% endif %}

{% if user.userprofile.user_type != 'seller' %}
<a style="margin-left: 90px; margin-bottom: 20px; background-color: #008787" href="/shoppingCart/"
   class="btn btn-primary ml-auto shadow"><strong>Shopping
    Cart</strong></a>
{% endif %}

{% if user.userprofile.user_type != 'seller' %}
<a style="margin-left: 20px; margin-bottom: 20px; background-color: #008787" href="/order_history/"
   class="btn btn-primary ml-auto shadow"><strong>Order History</strong></a>
{% endif %}
{% if error_message %}
<div id="error-message" class="alert alert-danger">{{ error_message }}</div>
{% endif %}

{% if user.userprofile.user_type == 'customer' %}
<div class="col-md-12 mb-3" style="margin-left: 80px">
    <form method="get" action="{% url 'products' %}" class="form-inline">
        <div class="form-group">
            <select name="category" class="form-control mr-2" style="width: 400px; display: inline">
                <option value="">See All</option> 
                {% for category in categories %}
                <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>
    </form>
</div>
{% endif %}


<div style="margin-left: 60px;width: 90%;" class="row">

    {% for product in products %}
    <div class="col-md-3 mb-3">
        <div class="card product-card shadow-lg rounded">
            <img src="{{ product.img }}" class="card-img-top" alt="{{ product.name }}" width="200px" height="200px">
            <div class="card-body" style="background-color: #00BFBF; ">
                <h5 class="card-title" style="font-family: 'Inter', sans-serif;"><strong>{{ product.name }}</strong>
                </h5>
                <p class="card-text"><strong>Description:</strong> {{ product.desc }}</p>
                <p class="card-text"><strong>Sex:</strong> {{ product.sex }}</p>
                <p class="card-text"><strong>Price:</strong> {{ product.price }}$</p>
                <p class="card-text"><strong>Stock:</strong> {{ product.stock }}</p>
                <p class="card-text"><strong>Color:</strong> {{ product.color }}</p>
                <p class="card-text"><strong>Category:</strong> {{ product.category }}</p>
                {% if user.userprofile.user_type == 'customer' %}
                <form method="post" action="{% url 'add_to_cart' product.id %}">
                    {% csrf_token %}
                    <label for="quantity"><strong>Quantity:</strong></label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" required
                           style="background-color: #B5FFFF">
                    <button type="submit" style="margin-top:10px;background-color: #008787"
                            class="btn btn-success shadow"><strong>Add
                        to Cart</strong>
                    </button>
                </form>
                {% endif %}
                {% if user.userprofile.user_type == 'seller' %}
                <a style="background-color: #008787;" href="{% url 'edit_product' product.id %}"
                   class="btn btn-primary shadow"><strong>Edit</strong></a>
                <a href="{% url 'delete_product' product.id %}"
                   class="btn btn-danger shadow"><strong>Delete</strong></a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>


</body>
</html>